<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\SimpleBlog42\Repository;

use Eccube\Repository\AbstractRepository;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Plugin\SimpleBlog42\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Category::class);
    }

    /**
     * タグを保存する.
     *
     * @param  Category $tag タグ
     */
    public function save($category)
    {
        if (!$category->getId()) {
            $sortNoTop = $this->findOneBy([], ['sort_no' => 'DESC']);
            $sort_no = 0;
            if (!is_null($sortNoTop)) {
                $sort_no = $sortNoTop->getSortNo();
            }

            $category->setSortNo($sort_no + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($category);
        $em->flush();
    }

    /**
     * タグ一覧を取得する.
     *
     * @return Category[] タグの配列
     */
    public function getList()
    {
        $qb = $this->createQueryBuilder('t')->orderBy('t.sort_no', 'DESC');

        return $qb->getQuery()->getResult();
    }

    /**
     * カテゴリーを削除する.
     *
     * @param  Category $Category 削除対象のタグ
     */
    public function delete($Category)
    {
        $em = $this->getEntityManager();
        $em->beginTransaction();

        $em->createQuery("DELETE \Plugin\SimpleBlog42\Entity\BlogCategory bc WHERE bc.Category = :category")->execute(['category' => $Category]);

        $this
            ->createQueryBuilder('t')
            ->update()
            ->set('t.sort_no', 't.sort_no - 1')
            ->where('t.sort_no > :sort_no')
            ->setParameter('sort_no', $Category->getSortNo())
            ->getQuery()
            ->execute();

        $em->remove($Category);
        $em->flush();

        $em->commit();
    }
}
